apiVersion: v1
kind: ConfigMap
metadata:
  name: ttb-backend-api-configmap
data:
  mongo-db-host: ttbcluster.5ixsmyc.mongodb.net/?appName=ttbcluster
  mongo-db-name: ttb
  allowed-cors: http://localhost:3000,http://ttb-front-app-platform-service:3000,https://app.tracktobuy.com